// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hdzacp_null_moments_cpp
Rcpp::List hdzacp_null_moments_cpp(const int n, const int mn);
RcppExport SEXP _HDZACP_hdzacp_null_moments_cpp(SEXP nSEXP, SEXP mnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type mn(mnSEXP);
    rcpp_result_gen = Rcpp::wrap(hdzacp_null_moments_cpp(n, mn));
    return rcpp_result_gen;
END_RCPP
}
// hdzacp_scan_rank_cpp
Rcpp::NumericVector hdzacp_scan_rank_cpp(const Rcpp::IntegerMatrix rank_matrix, const Rcpp::IntegerVector order, const Rcpp::NumericVector mu_full, const Rcpp::NumericVector sd_full, const int mn);
RcppExport SEXP _HDZACP_hdzacp_scan_rank_cpp(SEXP rank_matrixSEXP, SEXP orderSEXP, SEXP mu_fullSEXP, SEXP sd_fullSEXP, SEXP mnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix >::type rank_matrix(rank_matrixSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type mu_full(mu_fullSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type sd_full(sd_fullSEXP);
    Rcpp::traits::input_parameter< const int >::type mn(mnSEXP);
    rcpp_result_gen = Rcpp::wrap(hdzacp_scan_rank_cpp(rank_matrix, order, mu_full, sd_full, mn));
    return rcpp_result_gen;
END_RCPP
}
// hdzacp_test_rank_cpp
Rcpp::List hdzacp_test_rank_cpp(const Rcpp::IntegerMatrix rank_matrix, const int mn, const int n_perm, const int seed, const Rcpp::NumericVector mu_full, const Rcpp::NumericVector sd_full, const bool keep_orbit);
RcppExport SEXP _HDZACP_hdzacp_test_rank_cpp(SEXP rank_matrixSEXP, SEXP mnSEXP, SEXP n_permSEXP, SEXP seedSEXP, SEXP mu_fullSEXP, SEXP sd_fullSEXP, SEXP keep_orbitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix >::type rank_matrix(rank_matrixSEXP);
    Rcpp::traits::input_parameter< const int >::type mn(mnSEXP);
    Rcpp::traits::input_parameter< const int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type mu_full(mu_fullSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type sd_full(sd_fullSEXP);
    Rcpp::traits::input_parameter< const bool >::type keep_orbit(keep_orbitSEXP);
    rcpp_result_gen = Rcpp::wrap(hdzacp_test_rank_cpp(rank_matrix, mn, n_perm, seed, mu_full, sd_full, keep_orbit));
    return rcpp_result_gen;
END_RCPP
}
// hdzacp_size_simulate_cpp
Rcpp::List hdzacp_size_simulate_cpp(const int n, const int p, const double eta, const int n_rep, const int seed, const int n_threads, const std::string design, const double rho, const int block_size);
RcppExport SEXP _HDZACP_hdzacp_size_simulate_cpp(SEXP nSEXP, SEXP pSEXP, SEXP etaSEXP, SEXP n_repSEXP, SEXP seedSEXP, SEXP n_threadsSEXP, SEXP designSEXP, SEXP rhoSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const int >::type n_rep(n_repSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const std::string >::type design(designSEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(hdzacp_size_simulate_cpp(n, p, eta, n_rep, seed, n_threads, design, rho, block_size));
    return rcpp_result_gen;
END_RCPP
}
// hdzacp_ou_max_cpp
Rcpp::NumericMatrix hdzacp_ou_max_cpp(const int n_paths, const int n_grid, const double L_eta, const int n_threads, const int seed);
RcppExport SEXP _HDZACP_hdzacp_ou_max_cpp(SEXP n_pathsSEXP, SEXP n_gridSEXP, SEXP L_etaSEXP, SEXP n_threadsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n_paths(n_pathsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_grid(n_gridSEXP);
    Rcpp::traits::input_parameter< const double >::type L_eta(L_etaSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(hdzacp_ou_max_cpp(n_paths, n_grid, L_eta, n_threads, seed));
    return rcpp_result_gen;
END_RCPP
}
// hdzacp_hdd_distance_matrix_cpp
Rcpp::NumericMatrix hdzacp_hdd_distance_matrix_cpp(const Rcpp::NumericMatrix data);
RcppExport SEXP _HDZACP_hdzacp_hdd_distance_matrix_cpp(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(hdzacp_hdd_distance_matrix_cpp(data));
    return rcpp_result_gen;
END_RCPP
}
// hdzacp_hdd_stat_from_distance_cpp
Rcpp::NumericVector hdzacp_hdd_stat_from_distance_cpp(const Rcpp::NumericMatrix distance_matrix, const Rcpp::IntegerVector order);
RcppExport SEXP _HDZACP_hdzacp_hdd_stat_from_distance_cpp(SEXP distance_matrixSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type distance_matrix(distance_matrixSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(hdzacp_hdd_stat_from_distance_cpp(distance_matrix, order));
    return rcpp_result_gen;
END_RCPP
}
// hdzacp_max_endpoint_dp_cpp
Rcpp::List hdzacp_max_endpoint_dp_cpp(const double t, const double theta, const Rcpp::IntegerVector checkpoints);
RcppExport SEXP _HDZACP_hdzacp_max_endpoint_dp_cpp(SEXP tSEXP, SEXP thetaSEXP, SEXP checkpointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type checkpoints(checkpointsSEXP);
    rcpp_result_gen = Rcpp::wrap(hdzacp_max_endpoint_dp_cpp(t, theta, checkpoints));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HDZACP_hdzacp_null_moments_cpp", (DL_FUNC) &_HDZACP_hdzacp_null_moments_cpp, 2},
    {"_HDZACP_hdzacp_scan_rank_cpp", (DL_FUNC) &_HDZACP_hdzacp_scan_rank_cpp, 5},
    {"_HDZACP_hdzacp_test_rank_cpp", (DL_FUNC) &_HDZACP_hdzacp_test_rank_cpp, 7},
    {"_HDZACP_hdzacp_size_simulate_cpp", (DL_FUNC) &_HDZACP_hdzacp_size_simulate_cpp, 9},
    {"_HDZACP_hdzacp_ou_max_cpp", (DL_FUNC) &_HDZACP_hdzacp_ou_max_cpp, 5},
    {"_HDZACP_hdzacp_hdd_distance_matrix_cpp", (DL_FUNC) &_HDZACP_hdzacp_hdd_distance_matrix_cpp, 1},
    {"_HDZACP_hdzacp_hdd_stat_from_distance_cpp", (DL_FUNC) &_HDZACP_hdzacp_hdd_stat_from_distance_cpp, 2},
    {"_HDZACP_hdzacp_max_endpoint_dp_cpp", (DL_FUNC) &_HDZACP_hdzacp_max_endpoint_dp_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_HDZACP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
