# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hdzacp_null_moments_cpp <- function(n, mn) {
    .Call(`_HDZACP_hdzacp_null_moments_cpp`, n, mn)
}

hdzacp_scan_rank_cpp <- function(rank_matrix, order, mu_full, sd_full, mn) {
    .Call(`_HDZACP_hdzacp_scan_rank_cpp`, rank_matrix, order, mu_full, sd_full, mn)
}

hdzacp_test_rank_cpp <- function(rank_matrix, mn, n_perm, seed, mu_full, sd_full, keep_orbit = FALSE) {
    .Call(`_HDZACP_hdzacp_test_rank_cpp`, rank_matrix, mn, n_perm, seed, mu_full, sd_full, keep_orbit)
}

hdzacp_size_simulate_cpp <- function(n, p, eta, n_rep, seed, n_threads, design = "independent", rho = 0.0, block_size = 5L) {
    .Call(`_HDZACP_hdzacp_size_simulate_cpp`, n, p, eta, n_rep, seed, n_threads, design, rho, block_size)
}

hdzacp_ou_max_cpp <- function(n_paths, n_grid, L_eta, n_threads, seed) {
    .Call(`_HDZACP_hdzacp_ou_max_cpp`, n_paths, n_grid, L_eta, n_threads, seed)
}

hdzacp_hdd_distance_matrix_cpp <- function(data) {
    .Call(`_HDZACP_hdzacp_hdd_distance_matrix_cpp`, data)
}

hdzacp_hdd_stat_from_distance_cpp <- function(distance_matrix, order) {
    .Call(`_HDZACP_hdzacp_hdd_stat_from_distance_cpp`, distance_matrix, order)
}

hdzacp_max_endpoint_dp_cpp <- function(t, theta, checkpoints) {
    .Call(`_HDZACP_hdzacp_max_endpoint_dp_cpp`, t, theta, checkpoints)
}

